[versions]
coroutines = "1.10.1"
dependency-check = "12.0.2"
sonarqube = "6.0.1.5171"
spotless = "7.0.2"
kotlin = "2.1.10"
ktor = "3.1.0"
presentation-exchange = "0.3.0"
nimbus-sdk = "11.23"
uri-kmp = "0.0.19"
java = "17"
ktlint = "0.50.0"
dokka = "2.0.0"
maven-publish = "0.30.0"
fasterxml-jackson = "2.18.2"
bouncyCastle = "1.80"

[libraries]
fasterxml-jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "fasterxml-jackson" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
presentation-exchange = { module = "eu.europa.ec.eudi:eudi-lib-jvm-presentation-exchange-kt", version.ref = "presentation-exchange" }
nimbus-oauth2-oidc-sdk = { module = "com.nimbusds:oauth2-oidc-sdk", version.ref = "nimbus-sdk" }
uri-kmp = { module = "com.eygraber:uri-kmp", version.ref = "uri-kmp" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
bouncy-castle = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncyCastle" }

[plugins]
dependency-check = { id = "org.owasp.dependencycheck", version.ref = "dependency-check" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
